import Link from "next/link";
import { ArrowRight, Award, BookCheck, CalendarCheck, Check, CirclePlay, Clock3, Download, FileCheck2, MessageCircle, ShieldCheck, Users } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { defaultCourse } from "@/lib/content/defaults";

const curriculum = [
  ["Foundation", "Act structure, definitions, assessee, assessment year ও core taxability"],
  ["Taxability", "Residential status, scope of income, exclusions ও exemptions"],
  ["Heads of Income", "Salary, rent, agriculture, business, capital gain ও other sources"],
  ["Computation", "Total income, rebate, minimum tax, surcharge ও tax liability"],
  ["TDS Compliance", "Deduction/collection workflow, deposit, return ও practical checklist"],
  ["Return", "Individual return preparation, documents, schedules ও filing readiness"],
] as const;

export function CourseLanding() {
  return <>
    <section className="overflow-hidden bg-brand-navy py-14 text-white sm:py-20"><div className="section-shell grid items-center gap-10 lg:grid-cols-[1.12fr_0.88fr]"><div><Badge className="bg-brand-gold text-brand-navy">Live professional course</Badge><h1 className="font-heading mt-6 text-4xl leading-tight font-extrabold sm:text-6xl">{defaultCourse.title}</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-white/70">{defaultCourse.subtitle}। আইনকে practical calculation, compliance ও return workflow-এ রূপ দিন।</p><div className="mt-7 flex flex-wrap gap-4 text-sm text-white/70"><span className="flex items-center gap-2"><CirclePlay className="h-4 w-4 text-brand-gold" />Live + recorded</span><span className="flex items-center gap-2"><Users className="h-4 w-4 text-brand-gold" />Guided batch</span><span className="flex items-center gap-2"><Award className="h-4 w-4 text-brand-gold" />Certificate</span></div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button size="lg" asChild className="clicky bg-white text-brand-navy hover:bg-white/90"><Link href="/checkout?product=income-tax-working-framework">এনরোল করুন<ArrowRight /></Link></Button><Button size="lg" variant="outline" asChild className="clicky border-white/25 bg-transparent text-white hover:bg-white/10 hover:text-white"><Link href="#curriculum">Curriculum দেখুন</Link></Button></div></div><div className="premium-shadow rounded-[2rem] border border-white/12 bg-white/[0.075] p-6 sm:p-8"><p className="text-xs font-bold tracking-[0.16em] text-brand-gold uppercase">Course at a glance</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{[[CalendarCheck, "Live cohort", "Structured weekly class"], [Clock3, "Flexible access", "Class recordings"], [Download, "Resources", "PDF & working files"], [MessageCircle, "Support", "Community discussion"]].map(([Icon, title, text]) => { const IconComponent = Icon as typeof Clock3; return <div key={String(title)} className="rounded-xl bg-white/8 p-4"><IconComponent className="h-5 w-5 text-brand-gold" /><p className="mt-3 font-semibold">{String(title)}</p><p className="mt-1 text-xs text-white/50">{String(text)}</p></div>; })}</div><div className="mt-6 border-t border-white/10 pt-6"><div className="flex items-end justify-between"><div><p className="text-xs text-white/50">Course fee</p><p className="font-heading text-4xl font-bold">৳ {defaultCourse.price.toLocaleString("bn-BD")}</p></div><span className="text-sm text-white/40 line-through">৳ {defaultCourse.compareAtPrice.toLocaleString("bn-BD")}</span></div></div></div></div></section>

    <section className="py-16 sm:py-22"><div className="section-shell grid gap-5 md:grid-cols-3">{[[BookCheck, "Framework-first", "ছড়িয়ে থাকা tax provision-কে একটি clear working sequence-এ সাজানো।"], [FileCheck2, "Practice-ready", "Calculation, document ও return-ready resources দিয়ে অনুশীলন।"], [ShieldCheck, "Current & reliable", "Updated law এবং professional context অনুযায়ী শেখানো।"]].map(([Icon, title, text]) => { const IconComponent = Icon as typeof BookCheck; return <Card key={String(title)} className="py-0"><CardContent className="p-6"><IconComponent className="h-6 w-6 text-brand-gold" /><h2 className="font-heading mt-5 text-2xl font-bold">{String(title)}</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">{String(text)}</p></CardContent></Card>; })}</div></section>

    <section id="curriculum" className="bg-white/70 py-16 sm:py-22"><div className="section-shell grid gap-10 lg:grid-cols-[0.72fr_1.28fr]"><div><p className="text-xs font-bold tracking-[0.16em] text-brand-gold uppercase">CURRICULUM</p><h2 className="font-heading mt-3 text-4xl font-extrabold sm:text-5xl">Act থেকে Return—complete learning path</h2><p className="mt-4 leading-8 text-muted-foreground">প্রতিটি module আগের module-এর ওপর build করে, যেন learning fragmented না হয়।</p></div><div className="space-y-3">{curriculum.map(([title, text], index) => <div key={title} className="flex gap-4 rounded-2xl border border-brand-navy/10 bg-card p-5"><span className="font-mono mt-1 text-xs font-bold text-brand-gold">0{index + 1}</span><div><h3 className="font-heading text-xl font-bold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div></div>)}</div></div></section>

    <section className="py-16 sm:py-22"><div className="section-shell"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-bold tracking-[0.16em] text-brand-gold uppercase">WHAT YOU GET</p><h2 className="font-heading mt-3 text-4xl font-extrabold">একটি course-এর চেয়েও বেশি</h2></div><div className="mx-auto mt-10 grid max-w-5xl gap-3 sm:grid-cols-2">{["Live interactive classes", "Recorded class access", "Module-wise practical resources", "Google Calendar class reminder", "Meet join link from dashboard", "Community support access", "Completion certificate", "Future update-ready dashboard"].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl border border-brand-navy/10 bg-white p-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-brand-gold/15 text-brand-gold"><Check className="h-4 w-4" /></span><span className="font-semibold">{item}</span></div>)}</div></div></section>

    <section className="bg-[#e9e0d1] py-16 sm:py-22"><div className="section-shell grid items-start gap-10 lg:grid-cols-2"><div><p className="text-xs font-bold tracking-[0.16em] text-brand-gold uppercase">FREQUENTLY ASKED</p><h2 className="font-heading mt-3 text-4xl font-extrabold">আপনার প্রশ্নের উত্তর</h2><p className="mt-4 text-muted-foreground">Enrollment-এর আগে গুরুত্বপূর্ণ বিষয়গুলো জেনে নিন।</p></div><Accordion type="single" collapsible className="rounded-2xl border bg-card px-5"><AccordionItem value="a"><AccordionTrigger>কোর্সটি কাদের জন্য?</AccordionTrigger><AccordionContent>Tax learner, accounts/legal professional, practitioner, student এবং Income Tax Act practicalভাবে শিখতে চান—এমন সবার জন্য।</AccordionContent></AccordionItem><AccordionItem value="b"><AccordionTrigger>Live class miss হলে কী হবে?</AccordionTrigger><AccordionContent>Paid learner dashboard-এ recording publish হলে সেখান থেকে দেখা যাবে। Access period batch setting অনুযায়ী নির্ধারিত হবে।</AccordionContent></AccordionItem><AccordionItem value="c"><AccordionTrigger>Payment কীভাবে verify হবে?</AccordionTrigger><AccordionContent>PayStation transaction server-to-server verify হওয়ার পরই enrollment active হবে। Browser success page একা কোনো access চালু করতে পারবে না।</AccordionContent></AccordionItem><AccordionItem value="d"><AccordionTrigger>Certificate কীভাবে যাচাই করা যাবে?</AccordionTrigger><AccordionContent>Public verification code দিয়ে `/verify` page-এ PII-safe certificate information দেখা যাবে।</AccordionContent></AccordionItem></Accordion></div></section>

    <section className="bg-brand-navy py-16 text-center text-white"><div className="section-shell"><h2 className="font-heading text-4xl font-extrabold sm:text-5xl">Income Tax working confidence তৈরি করুন</h2><p className="mx-auto mt-4 max-w-2xl text-white/65">Structured framework, live guidance ও practical resource-এর সঙ্গে শেখা শুরু করুন।</p><Button size="lg" asChild className="clicky mt-8 bg-white text-brand-navy hover:bg-white/90"><Link href="/checkout?product=income-tax-working-framework">এখনই এনরোল করুন<ArrowRight /></Link></Button></div></section>
  </>;
}
